python scripts\gnn_central.py --num_sample 32 --dist_thresh 1
python scripts\gnn_central.py --num_sample 64 --dist_thresh 1
python scripts\gnn_central.py --num_sample 128 --dist_thresh 1
python scripts\gnn_central.py --num_sample 256 --dist_thresh 1
python scripts\gnn_central.py --num_sample 32 --dist_thresh 0.1
python scripts\gnn_central.py --num_sample 64 --dist_thresh 0.1
python scripts\gnn_central.py --num_sample 128 --dist_thresh 0.1
python scripts\gnn_central.py --num_sample 256 --dist_thresh 0.1
python scripts\gnn_central.py --num_sample 32 --dist_thresh 0.5
python scripts\gnn_central.py --num_sample 64 --dist_thresh 0.5
python scripts\gnn_central.py --num_sample 128 --dist_thresh 0.5
python scripts\gnn_central.py --num_sample 256 --dist_thresh 0.5